remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

navbar:
  left:
    - text: "Introduction"
    - ahref: index.md
    - text: "Roles in Azure"
    - ahref: first_page.md
    - text: "SQL Server and VM"
    - ahref: sql-server-vm.md